<a href="https://colab.research.google.com/github/dineshdb02/practise-/blob/main/final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/stores_data_set.csv')
df1=pd.read_csv('/content/sales_data_set.csv')

In [ ]:
df.info()

In [ ]:
df.groupby("Type")["Size"].mean().astype(int)
# df.groupby("Type")["Size"].mean().astype(int)

Type
A    177247.727273
B    101190.705882
C     40541.666667
Name: Size, dtype: float64

In [ ]:
df.Type.unique()

array(['A', 'B', 'C'], dtype=object)

In [ ]:

df1

        Store  Dept        Date  Weekly_Sales  IsHoliday
0           1     1  05/02/2010      24924.50      False
1           1     1  12/02/2010      46039.49       True
2           1     1  19/02/2010      41595.55      False
3           1     1  26/02/2010      19403.54      False
4           1     1  05/03/2010      21827.90      False
...       ...   ...         ...           ...        ...
421565     45    98  28/09/2012        508.37      False
421566     45    98  05/10/2012        628.10      False
421567     45    98  12/10/2012       1061.02      False
421568     45    98  19/10/2012        760.01      False
421569     45    98  26/10/2012       1076.80      False

[421570 rows x 5 columns]

In [ ]:
df1.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
dtype: int64

In [ ]:
def avg(Year):
  db=df1[df1['Date'].dt.year.eq(Year) ].groupby(df1["IsHoliday"]==True)['Weekly_Sales'].mean().astype(int)
  return db
# df1.groupby(df1['IsHoliday'])['Weekly_Sales'].sum().astype(int)

In [ ]:
avg(2012)

IsHoliday
False    15656
True     16480
Name: Weekly_Sales, dtype: int64

In [ ]:
df1[df1['Date'].dt.year.eq(2011)].groupby(df1["IsHoliday"]==False)["Weekly_Sales"].sum().astype(int)
# df1[df1['Date'].dt.year.eq(2012)].groupby(df1["IsHoliday"]==False)["Weekly_Sales"].sum().astype(int)

IsHoliday
False     37281796
True     400560961
Name: Weekly_Sales, dtype: int64

In [ ]:
df1[df1['Date'].dt.year.eq(2012)].groupby(df1["IsHoliday"]==False)["Weekly_Sales"].sum().astype(int)

IsHoliday
False      98339467
True     1901793392
Name: Weekly_Sales, dtype: int64

In [ ]:
df1['Date'] = pd.to_datetime(df1['Date'])

ValueError: time data "19/02/2010" doesn't match format "%m/%d/%Y", at position 2. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
df1['Date'] = pd.to_datetime(df1['Date'], format="%d/%m/%Y")

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134761 entries, 0 to 134760
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         134761 non-null  int64
 1   Dept          134761 non-null  int64
 2   Date          134761 non-null  datetime64[ns]
 3   Weekly_Sales  134761 non-null  float64
 4   IsHoliday     134761 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 5.1+ MB

In [ ]:
df1.head()

   Store  Dept       Date  Weekly_Sales IsHoliday
0      1     1 2010-02-05      24924.50     False
1      1     1 2010-02-12      46039.49      True
2      1     1 2010-02-19      41595.55     False
3      1     1 2010-02-26      19403.54     False
4      1     1 2010-03-05      21827.90     False

In [ ]:
df1['Date'].head()

0   2010-02-05
1   2010-02-12
2   2010-02-19
3   2010-02-26
4   2010-03-05
Name: Date, dtype: datetime64[ns]

In [ ]:
df2=pd.read_csv('/content/Features_data_set.csv')
df2

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,12/02/2010,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,19/02/2010,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,26/02/2010,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,05/03/2010,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8185,45,28/06/2013,76.05,3.639,4842.29,975.03,3.00,2449.97,3169.69,NaN,NaN,False
8186,45,05/07/2013,77.50,3.614,9090.48,2268.58,582.74,5797.47,1514.93,NaN,NaN,False
8187,45,12/07/2013,79.37,3.614,3789.94,1827.31,85.72,744.84,2150.36,NaN,NaN,False
8188,45,19/07/2013,82.84,3.737,2961.49,1047.07,204.19,363.00,1059.46,NaN,NaN,False
8189,45,26/07/2013,76.06,3.804,212.02,851.73,2.06,10.88,1864.57,NaN,NaN,False

In [ ]:
df2['Date'] = pd.to_datetime(df2['Date'], format="%d/%m/%Y")
df2[df2['Date'].dt.year.eq(2011) & df2['IsHoliday'].eq(True)]
# df2[df2['CPI'].sum()]

NameError: name 'df2' is not defined

In [ ]:
df3.Type.unique()

array(['A', 'B', 'C', nan], dtype=object)

In [ ]:
frames=[df,df1]
df3=pd.concat(frames)
df3

        Store Type      Size  Dept        Date  Weekly_Sales IsHoliday
0           1    A  151315.0   NaN         NaN           NaN       NaN
1           2    A  202307.0   NaN         NaN           NaN       NaN
2           3    B   37392.0   NaN         NaN           NaN       NaN
3           4    A  205863.0   NaN         NaN           NaN       NaN
4           5    B   34875.0   NaN         NaN           NaN       NaN
...       ...  ...       ...   ...         ...           ...       ...
421565     45  NaN       NaN  98.0  28/09/2012        508.37     False
421566     45  NaN       NaN  98.0  05/10/2012        628.10     False
421567     45  NaN       NaN  98.0  12/10/2012       1061.02     False
421568     45  NaN       NaN  98.0  19/10/2012        760.01     False
421569     45  NaN       NaN  98.0  26/10/2012       1076.80     False

[421615 rows x 7 columns]

In [ ]:
df3.groupby(df3["Type"]=="A" , df3["IsHoliday"]==True)['Weekly_Sales'].mean()

TypeError: unhashable type: 'Series'

In [ ]:
df3.groupby([df3["Type"]=="A" , df3["IsHoliday"]==True]).mean()

                     Store      Type      Size       Dept  \
Type  IsHoliday
False False      22.202565 -0.999811  130287.6  44.252633
      True       22.175078 -1.000000       NaN  44.361856

                                         Date  Weekly_Sales IsHoliday
Type  IsHoliday
False False     2011-06-19 09:20:40.552271104  15901.445069       0.0
      True      2011-06-04 16:21:21.683018240  17035.823187       1.0

In [ ]:
df3['Type'] = df3['Type'].astype('category').cat.codes

In [ ]:
df3.notnull().sum()

Store           68312
Type               45
Size               45
Dept            68267
Date            68267
Weekly_Sales    68267
IsHoliday       68266
dtype: int64

In [ ]:
df3.fillna(0)

       Store Type      Size  Dept                 Date  Weekly_Sales IsHoliday
0          1    A  151315.0   0.0                    0          0.00         0
1          2    A  202307.0   0.0                    0          0.00         0
2          3    B   37392.0   0.0                    0          0.00         0
3          4    A  205863.0   0.0                    0          0.00         0
4          5    B   34875.0   0.0                    0          0.00         0
...      ...  ...       ...   ...                  ...           ...       ...
68262      7    0       0.0  95.0  2011-06-17 00:00:00      34726.21     False
68263      7    0       0.0  95.0  2011-06-24 00:00:00      38203.12     False
68264      7    0       0.0  95.0  2011-07-01 00:00:00      42550.03     False
68265      7    0       0.0  95.0  2011-07-08 00:00:00      47194.97     False
68266      7    0       0.0  95.0  2011-07-15 00:00:00        411.00         0

[68312 rows x 7 columns]

In [ ]:
df3.groupby(df3["Type"]=="A")['Weekly_Sales'].mean().astype(float)

Type
False    15981.258123
True              NaN
Name: Weekly_Sales, dtype: float64

In [ ]:
df3.isnull().sum()

Store                0
Type            134761
Size            134761
Dept                45
Date                45
Weekly_Sales        45
IsHoliday           45
dtype: int64

In [ ]:
df3.fillna(0)

,Store,Type,Size,Dept,Date,Weekly_Sales,IsHoliday
0,1,A,151315.0,0.0,0,0.00,0
1,2,A,202307.0,0.0,0,0.00,0
2,3,B,37392.0,0.0,0,0.00,0
3,4,A,205863.0,0.0,0,0.00,0
4,5,B,34875.0,0.0,0,0.00,0
...,...,...,...,...,...,...,...
134756,14,0,0.0,55.0,2012-08-31 00:00:00,14583.10,FALSE
134757,14,0,0.0,55.0,2012-09-07 00:00:00,10658.23,TRUE
134758,14,0,0.0,55.0,2012-09-14 00:00:00,7357.03,FALSE
134759,14,0,0.0,55.0,2012-09-21 00:00:00,9152.70,FALSE
134760,14,0,0.0,55.0,2012-09-28 00:00:00,8459.48,FA

In [ ]:
di=pd.merge_ordered(df, df1,fill_method="ffill", left_by="Store")
di

       Store Type    Size  Dept        Date  Weekly_Sales IsHoliday
0          1    A  151315   1.0  05/02/2010      24924.50     False
1          1    A  151315   1.0  12/02/2010      46039.49      True
2          1    A  151315   1.0  19/02/2010      41595.55     False
3          1    A  151315   1.0  26/02/2010      19403.54     False
4          1    A  151315   1.0  05/03/2010      21827.90     False
...      ...  ...     ...   ...         ...           ...       ...
34078     41    A  196321   NaN         NaN           NaN       NaN
34079     42    C   39690   NaN         NaN           NaN       NaN
34080     43    C   41062   NaN         NaN           NaN       NaN
34081     44    C   39910   NaN         NaN           NaN       NaN
34082     45    B  118221   NaN         NaN           NaN       NaN

[34083 rows x 7 columns]

In [ ]:
di.Type.unique()

array(['A', 'B', 'C'], dtype=object)

In [ ]:
di.groupby(di["Type"])['Store'].count()

Type
A    25025
B     9052
C        6
Name: Store, dtype: int64

In [ ]:
di['Type']=="A"
di.groupby(di["IsHoliday"]==True)['Weekly_Sales'].mean()

IsHoliday
False    15901.445069
True     17035.823187
Name: Weekly_Sales, dtype: float64

In [ ]:
if di['Type'].iloc[0] == 'C':
  ind =di.groupby(di["IsHoliday"]==True)['Weekly_Sales'].mean()
print(ind)

IsHoliday
False    15901.445069
True     17035.823187
Name: Weekly_Sales, dtype: float64

In [ ]:
di.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68267 entries, 0 to 68266
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         68267 non-null  int64
 1   Type          68267 non-null  object
 2   Size          68267 non-null  int64
 3   Dept          68267 non-null  int64
 4   Date          68267 non-null  datetime64[ns]
 5   Weekly_Sales  68267 non-null  float64
 6   IsHoliday     68266 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(3), object(2)
memory usage: 3.6+ MB

In [ ]:
di['IsHoliday']=True

In [ ]:
di['Type'].unique()

array(['A', 'B'], dtype=object)

In [ ]:
di.groupby(di["IsHoliday"]==True and di['Type'])['Weekly_Sales'].mean()

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
di.groupby((di["IsHoliday"]==True) & (di['Type']=='C'))['Weekly_Sales'].mean()

False    16026.916204
True      9532.963131
Name: Weekly_Sales, dtype: float64

In [ ]:
for i in di['Type'].unique():
  if i== 'C':
    ind =di.groupby((di["IsHoliday"]) & (di['Type']=='i'))['Weekly_Sales'].mean()
    # indi =di.groupby((di["IsHoliday"]==True))['Weekly_Sales'].mean()
  print(ind)

False    15981.258123
Name: Weekly_Sales, dtype: float64
False    15981.258123
Name: Weekly_Sales, dtype: float64
False    15981.258123
Name: Weekly_Sales, dtype: float64

In [ ]:
def average(year):
  di['Date'] = pd.to_datetime(di['Date'], format="%d/%m/%Y")
  data=di[di['Date'].dt.year.eq(year)].groupby(di["IsHoliday"]==True)["Weekly_Sales"].mean().astype(int)
  return data

In [ ]:
def find_average(Type):
  for i in di['Type'].unique():
    if Type==i:


      return di.groupby((di["IsHoliday"]==True) & (di['Type']==Type))['Weekly_Sales'].mean()

In [ ]:
find_average('B')

In [ ]:
average(2011)

IsHoliday
False    15837
True     17343
Name: Weekly_Sales, dtype: int64

In [ ]:
di.groupby('Type')['Weekly_Sales'].mean()

Type
A    20099.568043
B    12237.075977
C     9519.532538
Name: Weekly_Sales, dtype: float64

In [ ]:
for i in di['Type'].unique():
  if i== 'A':
    print("A_value:","\n",di.groupby((di["IsHoliday"]) & (di['Type']==i))['Weekly_Sales'].mean().astype(int))
  elif i== 'B':
    print("B_value:","\n",di.groupby((di["IsHoliday"]) & (di['Type']==i))['Weekly_Sales'].mean().astype(int))
  elif i== 'C':
    print("C_value:","\n",di.groupby((di["IsHoliday"]) & (di['Type']==i))['Weekly_Sales'].mean().astype(int))

A_value:
 False    15782
True     21297
Name: Weekly_Sales, dtype: int64
B_value:
 False    16055
True     13346
Name: Weekly_Sales, dtype: int64
C_value:
 False    16026
True      9532
Name: Weekly_Sales, dtype: int64